#!/usr/bin/env npx tsx

/**
 * Regenerate the seed data files from the live goal_choreographies table.
 * Run this after editorial edits land in the DB so a future `seed.ts --apply`
 * reproduces exactly what players see instead of resurrecting stale content.
 *
 *   npx tsx scripts/guess-the-goal/export-from-db.ts
 *
 * The classics/modern split is preserved by reading the slug lists out of the
 * current files before overwriting them; goals not present in either (new
 * agent-generated content) default to modern.
 */

import { config as loadEnv } from 'dotenv';
import postgres from 'postgres';
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

loadEnv({ path: '.env.local' });
loadEnv();

const here = dirname(fileURLToPath(import.meta.url));
const J = (v: unknown) => JSON.stringify(v);

type Row = {
  slug: string;
  difficulty: string;
  title: unknown;
  options: unknown;
  fun_fact: unknown;
  bonus: unknown;
  players: unknown;
  steps: unknown;
  scorer: string;
  match_label: string;
  year: number;
  goal_ordinal: number;
  schema_version: number;
  video_url: string | null;
  clip_start_s: number | null;
  clip_end_s: number | null;
};

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  console.error('DATABASE_URL is required');
  process.exit(1);
}
const sql = postgres(databaseUrl, { max: 1, prepare: false });

const rows = await sql<Row[]>`
  SELECT slug, difficulty, title, options, fun_fact, bonus,
         players, steps, scorer, match_label, year, goal_ordinal,
         schema_version, video_url, clip_start_s, clip_end_s
    FROM goal_choreographies
   WHERE status = 'published'
   ORDER BY year, slug
`;
if (rows.length === 0) {
  console.error('no published goals found — refusing to overwrite seed files');
  process.exit(1);
}

function classicSlugList(): string[] {
  // Read the committed version, not the working tree: this script rewrites
  // both files, so after one run the working copy no longer carries the
  // original split (and its quote style changes too).
  try {
    const committed = execFileSync(
      'git',
      ['show', `HEAD:${relative(process.cwd(), join(here, 'goals-classics.data.ts'))}`],
      { encoding: 'utf8' }
    );
    return [...committed.matchAll(/slug: ["']([a-z0-9-]+)["']/g)].map((m) => m[1]);
  } catch {
    return [...readFileSync(join(here, 'goals-classics.data.ts'), 'utf8').matchAll(/slug: ["']([a-z0-9-]+)["']/g)]
      .map((m) => m[1]);
  }
}
const classicSlugs = new Set(classicSlugList());

function render(goal: Row): string {
  const lines: string[] = [];
  lines.push('  {');
  lines.push(`    slug: ${J(goal.slug)},`);
  lines.push(`    difficulty: ${J(goal.difficulty)},`);
  lines.push(`    title: ${J(goal.title)},`);
  lines.push(`    options: ${J(goal.options)},`);
  if (goal.fun_fact == null) lines.push('    fun_fact: null,');
  else lines.push(`    fun_fact: ${J(goal.fun_fact)},`);
  if (goal.bonus == null) lines.push('    bonus: null,');
  else lines.push(`    bonus: ${J(goal.bonus)},`);
  lines.push(`    players: ${J(goal.players)},`);
  lines.push(`    steps: ${J(goal.steps)},`);
  lines.push(`    scorer: ${J(goal.scorer)},`);
  lines.push(`    match_label: ${J(goal.match_label)},`);
  lines.push(`    year: ${goal.year},`);
  lines.push(`    goal_ordinal: ${goal.goal_ordinal},`);
  lines.push(`    schema_version: ${goal.schema_version},`);
  if (goal.clip_start_s != null && goal.clip_end_s != null) {
    lines.push(`    clip_start_s: ${goal.clip_start_s},`);
    lines.push(`    clip_end_s: ${goal.clip_end_s},`);
  }
  lines.push('  }');
  return lines.join('\n');
}

function fileFor(goals: Row[], varName: string): string {
  return (
    `import type { ChoreographyContent } from '../../src/modules/guess-the-goal/guess-the-goal.schemas.js';\n\n` +
    `/** AUTO-GENERATED by export-from-db.ts from the live DB — do not hand-edit.\n` +
    ` *  Regenerate with: npx tsx scripts/guess-the-goal/export-from-db.ts */\n\n` +
    `export const ${varName}: ChoreographyContent[] = [\n` +
    goals.map(render).join(',\n') +
    ',\n];\n'
  );
}

const classics = rows.filter((r) => classicSlugs.has(r.slug));
const modern = rows.filter((r) => !classicSlugs.has(r.slug));

writeFileSync(join(here, 'goals-classics.data.ts'), fileFor(classics, 'CLASSIC_GOALS'));
writeFileSync(join(here, 'goals-modern.data.ts'), fileFor(modern, 'MODERN_GOALS'));

const videos = Object.fromEntries(rows.filter((r) => r.video_url).map((r) => [r.slug, r.video_url]));
writeFileSync(join(here, 'goal-videos.json'), JSON.stringify(videos, null, 2) + '\n');

console.log(
  `exported ${rows.length} goals → classics ${classics.length} / modern ${modern.length}; ` +
  `${Object.keys(videos).length} video links; ` +
  `${rows.filter((r) => r.clip_start_s != null).length} clip windows`
);
await sql.end();
