import test from 'node:test';import assert from 'node:assert/strict';
import {contentHash} from '../../scripts/release/question-manifest.mjs';
import {buildAdditiveQuestionPackage} from '../../scripts/release/question-package.mjs';
import {buildStagingQuestionAlignmentPlan} from '../../scripts/release/question-alignment-plan.mjs';
import {buildQuestionPublicationPlan} from '../../scripts/release/question-publication.mjs';
import {buildStagingQuestionStatePlan,validateQuestionStatePlan,runStagingQuestionStateParity} from '../../scripts/release/question-state-parity.mjs';
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const snap=(project,ids)=>({format:1,project,categories:[{id:id(1),slug:'football',name:{en:'Football'},is_active:true,campaign_only:false}],questions:ids.map(n=>({id:id(n),category_id:id(1),type:'mcq_single',difficulty:'easy',status:'published',prompt:{en:'Question '+n},explanation:null,ranked_eligible:true,visibility:'public'})),payloads:ids.map(n=>({id:id(n+100),question_id:id(n),payload:{type:'mcq_single',options:[]}}))});
function fixture(){const stage=snap('nsdfiprfmhdqhbfxfwpv',[2,3]),prod=snap('lfbwhxvwubzeqkztghok',[2,4]);const pkg=buildAdditiveQuestionPackage(stage,prod,{conflictPolicy:'preserve-target-and-source-drafts'});const alignment=buildStagingQuestionAlignmentPlan(stage,prod,pkg);const publication=buildQuestionPublicationPlan(pkg,[id(3)],{verificationSha256:'a'.repeat(64)});return {stage,prod,pkg,alignment,publication,plan:buildStagingQuestionStatePlan(stage,prod,pkg,alignment,[publication],{verificationSha256:'a'.repeat(64)})};}
test('restores production-only publication in staging without changing source or shared questions',()=>{const f=fixture();assert.equal(f.plan.rows.length,1);assert.equal(f.plan.rows[0].id,id(4));assert.deepEqual(f.plan.rows[0].after,{status:'published',ranked_eligible:true});assert.equal(f.plan.retainedQuestionCount,3);assert.equal(validateQuestionStatePlan(f.plan,f.plan.sha256),f.plan);});
test('rejects stale snapshots and duplicate publications',()=>{const f=fixture();f.stage.questions[0].prompt.en='Late edit';assert.throws(()=>buildStagingQuestionStatePlan(f.stage,f.prod,f.pkg,f.alignment,[f.publication],{verificationSha256:'a'.repeat(64)}),/Exact reviewed/);const g=fixture();assert.throws(()=>buildStagingQuestionStatePlan(g.stage,g.prod,g.pkg,g.alignment,[g.publication,g.publication],{verificationSha256:'a'.repeat(64)}),/Duplicate publication/);});
test('a rehashed plan still cannot write visibility, prompt or payload',()=>{for(const field of ['visibility','prompt','payload']){const {plan}=fixture();plan.rows[0].after[field]='public';const{sha256,...body}=plan;plan.sha256=contentHash(body);assert.throws(()=>validateQuestionStatePlan(plan,plan.sha256),/state-only/);}});
test('rejects production and missing recovery evidence before connecting',async()=>{const {plan}=fixture();await assert.rejects(runStagingQuestionStateParity({databaseUrl:'postgresql://postgres@db.lfbwhxvwubzeqkztghok.supabase.co:5432/postgres?sslmode=require',plan,expectedSha256:plan.sha256,action:'apply'}),/exact direct\/session target/);await assert.rejects(runStagingQuestionStateParity({databaseUrl:'postgresql://postgres@db.nsdfiprfmhdqhbfxfwpv.supabase.co:5432/postgres?sslmode=require',plan,expectedSha256:plan.sha256,action:'apply'}),/recovery and rehearsal/);});
