import type { ObjectiveDefinition } from './objectives.types.js';

export const OBJECTIVE_DEFINITIONS = [
  {
    id: 'daily_play_3_online_matches',
    periodType: 'daily',
    title: { en: 'Play 3 Online Matches', ka: 'ითამაშე 3 ონლაინ მატჩი' },
    description: { en: 'Complete 3 online matches today.', ka: 'დაასრულე 3 ონლაინ მატჩი დღეს.' },
    icon: 'Gamepad2',
    target: 3,
    rewardCoins: 100,
    rewardXp: 50,
    active: true,
    primaryDaily: true,
    rule: { type: 'online_matches_completed' },
  },
  {
    id: 'daily_answer_15_correct',
    periodType: 'daily',
    title: { en: 'Answer 15 Correctly', ka: 'უპასუხე 15-ს სწორად' },
    description: { en: 'Answer 15 questions correctly today.', ka: 'უპასუხე 15 კითხვას სწორად დღეს.' },
    icon: 'Target',
    target: 15,
    rewardCoins: 120,
    rewardXp: 60,
    active: true,
    primaryDaily: true,
    rule: { type: 'correct_answers' },
  },
  {
    id: 'daily_score_second_half_goal',
    periodType: 'daily',
    title: { en: 'Second Half Strike', ka: 'მეორე ტაიმის გოლი' },
    description: { en: 'Score a goal in the second half.', ka: 'გაიტანე გოლი მეორე ტაიმში.' },
    icon: 'Goal',
    target: 1,
    rewardCoins: 150,
    rewardXp: 75,
    active: true,
    primaryDaily: true,
    rule: { type: 'second_half_goal' },
  },
  {
    id: 'daily_clean_sheet',
    periodType: 'daily',
    title: { en: 'Clean Sheet', ka: 'სუფთა ფურცელი' },
    description: { en: 'Finish a possession match without conceding a goal.', ka: 'დაასრულე ფლობის მატჩი გოლის გატანის გარეშე.' },
    icon: 'ShieldCheck',
    target: 1,
    rewardCoins: 200,
    rewardXp: 100,
    active: true,
    primaryDaily: true,
    rule: { type: 'clean_sheet' },
  },
  {
    id: 'daily_complete_all',
    periodType: 'daily',
    title: { en: 'Complete All Daily Objectives', ka: 'შეასრულე ყველა დღიური მიზანი' },
    description: { en: 'Complete every primary daily objective.', ka: 'შეასრულე ყველა ძირითადი დღიური მიზანი.' },
    icon: 'Trophy',
    target: 4,
    rewardCoins: 300,
    rewardXp: 150,
    active: true,
    rule: { type: 'complete_all_daily' },
  },
  {
    id: 'weekly_win_10_competitive',
    periodType: 'weekly',
    title: { en: 'Win 10 Competitive Matches', ka: 'მოიგე 10 კონკურენტული მატჩი' },
    description: { en: 'Win 10 ranked matches this week.', ka: 'მოიგე 10 რეიტინგული მატჩი ამ კვირას.' },
    icon: 'Crown',
    target: 10,
    rewardCoins: 600,
    rewardXp: 300,
    active: true,
    rule: { type: 'ranked_wins' },
  },
  {
    id: 'weekly_win_streak_3',
    periodType: 'weekly',
    title: { en: 'Build a 3-Match Win Streak', ka: 'შექმენი 3-მატჩიანი მოგების სერია' },
    description: { en: 'Reach a 3-match ranked win streak this week.', ka: 'მიაღწიე 3-მატჩიან რეიტინგულ მოგების სერიას ამ კვირას.' },
    icon: 'Flame',
    target: 3,
    rewardCoins: 500,
    rewardXp: 250,
    active: true,
    rule: { type: 'ranked_win_streak' },
  },
  {
    id: 'weekly_answer_50_correct_one_category',
    periodType: 'weekly',
    title: { en: 'Category Specialist', ka: 'კატეგორიის სპეციალისტი' },
    description: { en: 'Answer 50 questions correctly in one category this week.', ka: 'უპასუხე 50 კითხვას სწორად ერთ კატეგორიაში ამ კვირას.' },
    icon: 'Brain',
    target: 50,
    rewardCoins: 600,
    rewardXp: 300,
    active: true,
    rule: { type: 'correct_answers_single_category' },
  },
  {
    id: 'weekly_play_friend_custom_room',
    periodType: 'weekly',
    title: { en: 'Play With a Friend', ka: 'ითამაშე მეგობართან' },
    description: { en: 'Complete a custom room match with a friend.', ka: 'დაასრულე მორგებული ოთახის მატჩი მეგობართან.' },
    icon: 'Users',
    target: 1,
    rewardCoins: 300,
    rewardXp: 150,
    active: true,
    rule: { type: 'friend_custom_match' },
  },
  {
    id: 'weekly_complete_dailies_5_times',
    periodType: 'weekly',
    title: { en: 'Daily Discipline', ka: 'დღიური დისციპლინა' },
    description: { en: 'Complete all daily objectives on 5 different days this week.', ka: 'შეასრულე ყველა დღიური მიზანი 5 სხვადასხვა დღეს ამ კვირას.' },
    icon: 'CalendarCheck',
    target: 5,
    rewardCoins: 800,
    rewardXp: 400,
    active: true,
    rule: { type: 'complete_daily_sets' },
  },
] as const satisfies readonly ObjectiveDefinition[];

export const ACTIVE_OBJECTIVE_DEFINITIONS = OBJECTIVE_DEFINITIONS.filter(
  (definition) => definition.active
);

export const PRIMARY_DAILY_OBJECTIVE_IDS = OBJECTIVE_DEFINITIONS
  .filter((definition) => definition.periodType === 'daily' && 'primaryDaily' in definition && definition.primaryDaily)
  .map((definition) => definition.id);
