import type { ObjectiveDefinition } from './objectives.types.js';

export const OBJECTIVE_DEFINITIONS = [
  {
    id: 'daily_play_3_online_matches',
    periodType: 'daily',
    title: 'Play 3 Online Matches',
    description: 'Complete 3 online matches today.',
    icon: 'Gamepad2',
    target: 3,
    rewardCoins: 100,
    rewardXp: 50,
    active: true,
    primaryDaily: true,
    rule: { type: 'online_matches_completed' },
  },
  {
    id: 'daily_answer_15_correct',
    periodType: 'daily',
    title: 'Answer 15 Correctly',
    description: 'Answer 15 questions correctly today.',
    icon: 'Target',
    target: 15,
    rewardCoins: 120,
    rewardXp: 60,
    active: true,
    primaryDaily: true,
    rule: { type: 'correct_answers' },
  },
  {
    id: 'daily_score_second_half_goal',
    periodType: 'daily',
    title: 'Second Half Strike',
    description: 'Score a goal in the second half.',
    icon: 'Goal',
    target: 1,
    rewardCoins: 150,
    rewardXp: 75,
    active: true,
    primaryDaily: true,
    rule: { type: 'second_half_goal' },
  },
  {
    id: 'daily_clean_sheet',
    periodType: 'daily',
    title: 'Clean Sheet',
    description: 'Finish a possession match without conceding a goal.',
    icon: 'ShieldCheck',
    target: 1,
    rewardCoins: 200,
    rewardXp: 100,
    active: true,
    primaryDaily: true,
    rule: { type: 'clean_sheet' },
  },
  {
    id: 'daily_complete_all',
    periodType: 'daily',
    title: 'Complete All Daily Objectives',
    description: 'Complete every primary daily objective.',
    icon: 'Trophy',
    target: 4,
    rewardCoins: 300,
    rewardXp: 150,
    active: true,
    rule: { type: 'complete_all_daily' },
  },
  {
    id: 'weekly_win_10_competitive',
    periodType: 'weekly',
    title: 'Win 10 Competitive Matches',
    description: 'Win 10 ranked matches this week.',
    icon: 'Crown',
    target: 10,
    rewardCoins: 600,
    rewardXp: 300,
    active: true,
    rule: { type: 'ranked_wins' },
  },
  {
    id: 'weekly_win_streak_3',
    periodType: 'weekly',
    title: 'Build a 3-Match Win Streak',
    description: 'Reach a 3-match ranked win streak this week.',
    icon: 'Flame',
    target: 3,
    rewardCoins: 500,
    rewardXp: 250,
    active: true,
    rule: { type: 'ranked_win_streak' },
  },
  {
    id: 'weekly_answer_50_correct_one_category',
    periodType: 'weekly',
    title: 'Category Specialist',
    description: 'Answer 50 questions correctly in one category this week.',
    icon: 'Brain',
    target: 50,
    rewardCoins: 600,
    rewardXp: 300,
    active: true,
    rule: { type: 'correct_answers_single_category' },
  },
  {
    id: 'weekly_play_friend_custom_room',
    periodType: 'weekly',
    title: 'Play With a Friend',
    description: 'Complete a custom room match with a friend.',
    icon: 'Users',
    target: 1,
    rewardCoins: 300,
    rewardXp: 150,
    active: true,
    rule: { type: 'friend_custom_match' },
  },
  {
    id: 'weekly_complete_dailies_5_times',
    periodType: 'weekly',
    title: 'Daily Discipline',
    description: 'Complete all daily objectives on 5 different days this week.',
    icon: 'CalendarCheck',
    target: 5,
    rewardCoins: 800,
    rewardXp: 400,
    active: true,
    rule: { type: 'complete_daily_sets' },
  },
] as const satisfies readonly ObjectiveDefinition[];

export const ACTIVE_OBJECTIVE_DEFINITIONS = OBJECTIVE_DEFINITIONS.filter(
  (definition) => definition.active
);

export const PRIMARY_DAILY_OBJECTIVE_IDS = OBJECTIVE_DEFINITIONS
  .filter((definition) => definition.periodType === 'daily' && 'primaryDaily' in definition && definition.primaryDaily)
  .map((definition) => definition.id);
