export {
  questionsRepo,
  type CreateQuestionData,
  type UpdateQuestionData,
  type ListQuestionsFilter,
  type ListQuestionsResult,
} from './questions.repo.js';
export { questionsService } from './questions.service.js';
export { questionsController } from './questions.controller.js';
export {
  questionResponseSchema,
  listQuestionsQuerySchema,
  createQuestionSchema,
  updateQuestionSchema,
  updateStatusSchema,
  uuidParamSchema,
  bulkCreateQuestionsSchema,
  bulkCreateResponseSchema,
  findDuplicatesQuerySchema,
  duplicatesResponseSchema,
  checkDuplicatesSchema,
  checkDuplicatesResponseSchema,
  duplicateGroupSchema,
  duplicateTypeEnum,
  questionTypeEnum,
  difficultyEnum,
  statusEnum,
  toQuestionResponse,
  toPaginatedResponse,
  type QuestionResponse,
  type ListQuestionsQuery,
  type CreateQuestionRequest,
  type UpdateQuestionRequest,
  type UpdateStatusRequest,
  type UuidParam,
  type BulkCreateQuestionsRequest,
  type BulkCreateResponse,
  type FindDuplicatesQuery,
  type DuplicatesResponse,
  type CheckDuplicatesRequest,
  type CheckDuplicatesResponse,
  type DuplicateGroup,
  type DuplicateType,
  type QuestionType,
  type Difficulty,
  type Status,
  type PaginatedResponse,
} from './questions.schemas.js';
