export type { AuthClient } from './auth.client.js';
export { getAuthClient } from './supabase-auth-client.js';
export type { AuthProvider } from './auth.provider.js';
export { getAuthProvider } from './supabase-auth-provider.js';
export { authController } from './auth.controller.js';
export { authService } from './auth.service.js';
export {
  registerSchema,
  loginSchema,
  refreshSchema,
  forgotPasswordSchema,
  resetPasswordSchema,
  resetPasswordHeadersSchema,
  socialLoginSchema,
  socialLoginTokenSchema,
  georgianPhoneOtpStartSchema,
  georgianPhoneOtpVerifySchema,
  georgianPhoneLinkStartSchema,
  georgianPhoneLinkVerifySchema,
  supabaseSmsHookHeadersSchema,
  supabaseSmsHookSchema,
  smsOfficeCallbackQuerySchema,
  smsOfficeStatusHeadersSchema,
  smsOfficeStatusQuerySchema,
  authResponseSchema,
  messageResponseSchema,
  phoneLinkStartResponseSchema,
  smsOfficeStatusResponseSchema,
  socialLoginResponseSchema,
  toAuthResponse,
  type AuthSession,
  type AuthResponse,
  type RegisterRequest,
  type LoginRequest,
  type RefreshRequest,
  type ForgotPasswordRequest,
  type ResetPasswordRequest,
  type ResetPasswordHeaders,
  type SocialLoginRequest,
  type SocialLoginTokenRequest,
  type GeorgianPhoneOtpStartRequest,
  type GeorgianPhoneOtpVerifyRequest,
  type GeorgianPhoneLinkStartRequest,
  type GeorgianPhoneLinkVerifyRequest,
  type SupabaseSmsHookHeaders,
  type SupabaseSmsHookRequest,
  type SmsOfficeCallbackQuery,
  type SmsOfficeStatusHeaders,
  type SmsOfficeStatusQuery,
  type MessageResponse,
  type PhoneLinkStartResponse,
  type SmsOfficeStatusResponse,
  type SocialLoginResponse,
} from './auth.schemas.js';
