// GENERATED by scripts/sync-wl-crest-registry.ts from frontend-web-next/src/data/clubs.json — do not edit.
export interface CrestRegistryRow { id: string; value: string; label: string; logo: string }
export const CREST_REGISTRY: readonly CrestRegistryRow[] = [
 {
  "id": "arsenal",
  "value": "Arsenal",
  "label": "Arsenal",
  "logo": "arsenal.webp"
 },
 {
  "id": "aston-villa",
  "value": "Aston Villa",
  "label": "Aston Villa",
  "logo": "aston-villa.webp"
 },
 {
  "id": "blackburn-rovers",
  "value": "Blackburn Rovers",
  "label": "Blackburn Rovers",
  "logo": "blackburn-rovers.webp"
 },
 {
  "id": "chelsea",
  "value": "Chelsea",
  "label": "Chelsea",
  "logo": "chelsea.webp"
 },
 {
  "id": "everton",
  "value": "Everton",
  "label": "Everton",
  "logo": "everton.webp"
 },
 {
  "id": "leeds-united",
  "value": "Leeds United",
  "label": "Leeds United",
  "logo": "leeds-united.webp"
 },
 {
  "id": "leicester-city",
  "value": "Leicester City",
  "label": "Leicester City",
  "logo": "leicester-city.webp"
 },
 {
  "id": "liverpool",
  "value": "Liverpool",
  "label": "Liverpool",
  "logo": "liverpool.webp"
 },
 {
  "id": "manchester-city",
  "value": "Manchester City",
  "label": "Manchester City",
  "logo": "manchester-city.webp"
 },
 {
  "id": "manchester-united",
  "value": "Manchester United",
  "label": "Manchester United",
  "logo": "manchester-united.webp"
 },
 {
  "id": "newcastle-united",
  "value": "Newcastle United",
  "label": "Newcastle United",
  "logo": "newcastle-united.webp"
 },
 {
  "id": "nottingham-forest",
  "value": "Nottingham Forest",
  "label": "Nottingham Forest",
  "logo": "nottingham-forest.webp"
 },
 {
  "id": "sunderland",
  "value": "Sunderland",
  "label": "Sunderland",
  "logo": "sunderland.webp"
 },
 {
  "id": "tottenham-hotspur",
  "value": "Tottenham Hotspur",
  "label": "Tottenham Hotspur",
  "logo": "tottenham-hotspur.webp"
 },
 {
  "id": "west-ham-united",
  "value": "West Ham United",
  "label": "West Ham United",
  "logo": "west-ham-united.webp"
 },
 {
  "id": "athletic-club",
  "value": "Athletic Club",
  "label": "Athletic Club",
  "logo": "athletic-club.webp"
 },
 {
  "id": "atletico-de-madrid",
  "value": "Atlético de Madrid",
  "label": "Atlético de Madrid",
  "logo": "atletico-de-madrid.webp"
 },
 {
  "id": "ca-osasuna",
  "value": "CA Osasuna",
  "label": "CA Osasuna",
  "logo": "ca-osasuna.webp"
 },
 {
  "id": "celta-de-vigo",
  "value": "Celta de Vigo",
  "label": "Celta de Vigo",
  "logo": "celta-de-vigo.webp"
 },
 {
  "id": "fc-barcelona",
  "value": "FC Barcelona",
  "label": "FC Barcelona",
  "logo": "fc-barcelona.webp"
 },
 {
  "id": "rc-deportivo-de-la-coruna",
  "value": "RC Deportivo de La Coruña",
  "label": "RC Deportivo de La Coruña",
  "logo": "rc-deportivo-de-la-coruna.webp"
 },
 {
  "id": "rcd-espanyol",
  "value": "RCD Espanyol",
  "label": "RCD Espanyol",
  "logo": "rcd-espanyol.webp"
 },
 {
  "id": "real-betis",
  "value": "Real Betis",
  "label": "Real Betis",
  "logo": "real-betis.webp"
 },
 {
  "id": "real-madrid-cf",
  "value": "Real Madrid CF",
  "label": "Real Madrid CF",
  "logo": "real-madrid-cf.webp"
 },
 {
  "id": "real-sociedad",
  "value": "Real Sociedad",
  "label": "Real Sociedad",
  "logo": "real-sociedad.webp"
 },
 {
  "id": "real-zaragoza",
  "value": "Real Zaragoza",
  "label": "Real Zaragoza",
  "logo": "real-zaragoza.webp"
 },
 {
  "id": "sevilla-fc",
  "value": "Sevilla FC",
  "label": "Sevilla FC",
  "logo": "sevilla-fc.webp"
 },
 {
  "id": "valencia-cf",
  "value": "Valencia CF",
  "label": "Valencia CF",
  "logo": "valencia-cf.webp"
 },
 {
  "id": "villarreal-cf",
  "value": "Villarreal CF",
  "label": "Villarreal CF",
  "logo": "villarreal-cf.webp"
 },
 {
  "id": "ac-milan",
  "value": "AC Milan",
  "label": "AC Milan",
  "logo": "ac-milan.webp"
 },
 {
  "id": "acf-fiorentina",
  "value": "ACF Fiorentina",
  "label": "ACF Fiorentina",
  "logo": "acf-fiorentina.webp"
 },
 {
  "id": "as-roma",
  "value": "AS Roma",
  "label": "AS Roma",
  "logo": "as-roma.webp"
 },
 {
  "id": "atalanta-bc",
  "value": "Atalanta BC",
  "label": "Atalanta BC",
  "logo": "atalanta-bc.webp"
 },
 {
  "id": "bologna-fc-1909",
  "value": "Bologna FC 1909",
  "label": "Bologna FC 1909",
  "logo": "bologna-fc-1909.webp"
 },
 {
  "id": "genoa-cfc",
  "value": "Genoa CFC",
  "label": "Genoa CFC",
  "logo": "genoa-cfc.webp"
 },
 {
  "id": "inter-milan",
  "value": "Inter Milan",
  "label": "Inter Milan",
  "logo": "inter-milan.webp"
 },
 {
  "id": "juventus",
  "value": "Juventus",
  "label": "Juventus",
  "logo": "juventus.webp"
 },
 {
  "id": "palermo-fc",
  "value": "Palermo FC",
  "label": "Palermo FC",
  "logo": "palermo-fc.webp"
 },
 {
  "id": "parma-calcio-1913",
  "value": "Parma Calcio 1913",
  "label": "Parma Calcio 1913",
  "logo": "parma-calcio-1913.webp"
 },
 {
  "id": "sampdoria",
  "value": "Sampdoria",
  "label": "Sampdoria",
  "logo": "sampdoria.webp"
 },
 {
  "id": "ss-lazio",
  "value": "SS Lazio",
  "label": "SS Lazio",
  "logo": "ss-lazio.webp"
 },
 {
  "id": "ssc-napoli",
  "value": "SSC Napoli",
  "label": "SSC Napoli",
  "logo": "ssc-napoli.webp"
 },
 {
  "id": "torino-fc",
  "value": "Torino FC",
  "label": "Torino FC",
  "logo": "torino-fc.webp"
 },
 {
  "id": "1-fc-kaiserslautern",
  "value": "1. FC Kaiserslautern",
  "label": "1. FC Kaiserslautern",
  "logo": "1-fc-kaiserslautern.webp"
 },
 {
  "id": "1-fc-koln",
  "value": "1. FC Köln",
  "label": "1. FC Köln",
  "logo": "1-fc-koln.webp"
 },
 {
  "id": "bayer-04-leverkusen",
  "value": "Bayer 04 Leverkusen",
  "label": "Bayer 04 Leverkusen",
  "logo": "bayer-04-leverkusen.webp"
 },
 {
  "id": "borussia-dortmund",
  "value": "Borussia Dortmund",
  "label": "Borussia Dortmund",
  "logo": "borussia-dortmund.webp"
 },
 {
  "id": "borussia-monchengladbach",
  "value": "Borussia Mönchengladbach",
  "label": "Borussia Mönchengladbach",
  "logo": "borussia-monchengladbach.webp"
 },
 {
  "id": "eintracht-frankfurt",
  "value": "Eintracht Frankfurt",
  "label": "Eintracht Frankfurt",
  "logo": "eintracht-frankfurt.webp"
 },
 {
  "id": "fc-bayern-munich",
  "value": "FC Bayern Munich",
  "label": "FC Bayern Munich",
  "logo": "fc-bayern-munich.webp"
 },
 {
  "id": "fc-schalke-04",
  "value": "FC Schalke 04",
  "label": "FC Schalke 04",
  "logo": "fc-schalke-04.webp"
 },
 {
  "id": "fc-st-pauli",
  "value": "FC St. Pauli",
  "label": "FC St. Pauli",
  "logo": "fc-st-pauli.webp"
 },
 {
  "id": "hamburger-sv",
  "value": "Hamburger SV",
  "label": "Hamburger SV",
  "logo": "hamburger-sv.webp"
 },
 {
  "id": "hertha-bsc",
  "value": "Hertha BSC",
  "label": "Hertha BSC",
  "logo": "hertha-bsc.webp"
 },
 {
  "id": "sc-freiburg",
  "value": "SC Freiburg",
  "label": "SC Freiburg",
  "logo": "sc-freiburg.webp"
 },
 {
  "id": "tsv-1860-munich",
  "value": "TSV 1860 Munich",
  "label": "TSV 1860 Munich",
  "logo": "tsv-1860-munich.webp"
 },
 {
  "id": "vfb-stuttgart",
  "value": "VfB Stuttgart",
  "label": "VfB Stuttgart",
  "logo": "vfb-stuttgart.webp"
 },
 {
  "id": "werder-bremen",
  "value": "Werder Bremen",
  "label": "Werder Bremen",
  "logo": "werder-bremen.webp"
 },
 {
  "id": "as-monaco",
  "value": "AS Monaco",
  "label": "AS Monaco",
  "logo": "as-monaco.webp"
 },
 {
  "id": "as-saint-etienne",
  "value": "AS Saint-Étienne",
  "label": "AS Saint-Étienne",
  "logo": "as-saint-etienne.webp"
 },
 {
  "id": "fc-girondins-de-bordeaux",
  "value": "FC Girondins de Bordeaux",
  "label": "FC Girondins de Bordeaux",
  "logo": "fc-girondins-de-bordeaux.webp"
 },
 {
  "id": "losc-lille",
  "value": "LOSC Lille",
  "label": "LOSC Lille",
  "logo": "losc-lille.webp"
 },
 {
  "id": "montpellier-hsc",
  "value": "Montpellier HSC",
  "label": "Montpellier HSC",
  "logo": "montpellier-hsc.webp"
 },
 {
  "id": "ogc-nice",
  "value": "OGC Nice",
  "label": "OGC Nice",
  "logo": "ogc-nice.webp"
 },
 {
  "id": "olympique-de-marseille",
  "value": "Olympique de Marseille",
  "label": "Olympique de Marseille",
  "logo": "olympique-de-marseille.webp"
 },
 {
  "id": "olympique-lyonnais",
  "value": "Olympique Lyonnais",
  "label": "Olympique Lyonnais",
  "logo": "olympique-lyonnais.webp"
 },
 {
  "id": "paris-saint-germain",
  "value": "Paris Saint-Germain",
  "label": "Paris Saint-Germain",
  "logo": "paris-saint-germain.webp"
 },
 {
  "id": "rc-lens",
  "value": "RC Lens",
  "label": "RC Lens",
  "logo": "rc-lens.webp"
 },
 {
  "id": "rc-strasbourg-alsace",
  "value": "RC Strasbourg Alsace",
  "label": "RC Strasbourg Alsace",
  "logo": "rc-strasbourg-alsace.webp"
 },
 {
  "id": "stade-de-reims",
  "value": "Stade de Reims",
  "label": "Stade de Reims",
  "logo": "stade-de-reims.webp"
 },
 {
  "id": "stade-rennais-fc",
  "value": "Stade Rennais FC",
  "label": "Stade Rennais FC",
  "logo": "stade-rennais-fc.webp"
 },
 {
  "id": "galatasaray",
  "value": "Galatasaray",
  "label": "Galatasaray",
  "logo": "galatasaray.webp"
 },
 {
  "id": "fenerbahce",
  "value": "Fenerbahçe",
  "label": "Fenerbahçe",
  "logo": "fenerbahce.webp"
 },
 {
  "id": "besiktas",
  "value": "Beşiktaş",
  "label": "Beşiktaş",
  "logo": "besiktas.webp"
 },
 {
  "id": "trabzonspor",
  "value": "Trabzonspor",
  "label": "Trabzonspor",
  "logo": "trabzonspor.webp"
 },
 {
  "id": "istanbul-basaksehir",
  "value": "Başakşehir",
  "label": "Başakşehir",
  "logo": "istanbul-basaksehir.webp"
 },
 {
  "id": "alanyaspor",
  "value": "Alanyaspor",
  "label": "Alanyaspor",
  "logo": "alanyaspor.webp"
 },
 {
  "id": "samsunspor",
  "value": "Samsunspor",
  "label": "Samsunspor",
  "logo": "samsunspor.webp"
 },
 {
  "id": "goztepe",
  "value": "Göztepe",
  "label": "Göztepe",
  "logo": "goztepe.webp"
 },
 {
  "id": "konyaspor",
  "value": "Konyaspor",
  "label": "Konyaspor",
  "logo": "konyaspor.webp"
 },
 {
  "id": "gaziantep-fk",
  "value": "Gaziantep FK",
  "label": "Gaziantep FK",
  "logo": "gaziantep-fk.webp"
 },
 {
  "id": "kasimpasa",
  "value": "Kasımpaşa",
  "label": "Kasımpaşa",
  "logo": "kasimpasa.webp"
 },
 {
  "id": "eyupspor",
  "value": "Eyüpspor",
  "label": "Eyüpspor",
  "logo": "eyupspor.webp"
 },
 {
  "id": "caykur-rizespor",
  "value": "Çaykur Rizespor",
  "label": "Çaykur Rizespor",
  "logo": "caykur-rizespor.webp"
 },
 {
  "id": "kocaelispor",
  "value": "Kocaelispor",
  "label": "Kocaelispor",
  "logo": "kocaelispor.webp"
 },
 {
  "id": "genclerbirligi",
  "value": "Gençlerbirliği",
  "label": "Gençlerbirliği",
  "logo": "genclerbirligi.webp"
 },
 {
  "id": "erzurumspor",
  "value": "Erzurumspor",
  "label": "Erzurumspor",
  "logo": "erzurumspor.webp"
 },
 {
  "id": "amedspor",
  "value": "Amedspor",
  "label": "Amedspor",
  "logo": "amedspor.webp"
 },
 {
  "id": "corum-fk",
  "value": "Çorum FK",
  "label": "Çorum FK",
  "logo": "corum-fk.webp"
 },
 {
  "id": "bursaspor",
  "value": "Bursaspor",
  "label": "Bursaspor",
  "logo": "bursaspor.webp"
 },
 {
  "id": "antalyaspor",
  "value": "Antalyaspor",
  "label": "Antalyaspor",
  "logo": "antalyaspor.webp"
 },
 {
  "id": "afc-ajax",
  "value": "AFC Ajax",
  "label": "AFC Ajax",
  "logo": "afc-ajax.webp"
 },
 {
  "id": "feyenoord",
  "value": "Feyenoord",
  "label": "Feyenoord",
  "logo": "feyenoord.webp"
 },
 {
  "id": "psv-eindhoven",
  "value": "PSV Eindhoven",
  "label": "PSV Eindhoven",
  "logo": "psv-eindhoven.webp"
 },
 {
  "id": "fc-porto",
  "value": "FC Porto",
  "label": "FC Porto",
  "logo": "fc-porto.webp"
 },
 {
  "id": "sc-braga",
  "value": "SC Braga",
  "label": "SC Braga",
  "logo": "sc-braga.webp"
 },
 {
  "id": "sl-benfica",
  "value": "SL Benfica",
  "label": "SL Benfica",
  "logo": "sl-benfica.webp"
 },
 {
  "id": "sporting-cp",
  "value": "Sporting CP",
  "label": "Sporting CP",
  "logo": "sporting-cp.webp"
 },
 {
  "id": "celtic",
  "value": "Celtic",
  "label": "Celtic",
  "logo": "celtic.webp"
 },
 {
  "id": "rangers",
  "value": "Rangers",
  "label": "Rangers",
  "logo": "rangers.webp"
 },
 {
  "id": "boca-juniors",
  "value": "Boca Juniors",
  "label": "Boca Juniors",
  "logo": "boca-juniors.webp"
 },
 {
  "id": "independiente",
  "value": "Independiente",
  "label": "Independiente",
  "logo": "independiente.webp"
 },
 {
  "id": "racing-club",
  "value": "Racing Club",
  "label": "Racing Club",
  "logo": "racing-club.webp"
 },
 {
  "id": "river-plate",
  "value": "River Plate",
  "label": "River Plate",
  "logo": "river-plate.webp"
 },
 {
  "id": "san-lorenzo-de-almagro",
  "value": "San Lorenzo de Almagro",
  "label": "San Lorenzo de Almagro",
  "logo": "san-lorenzo-de-almagro.webp"
 },
 {
  "id": "corinthians",
  "value": "Corinthians",
  "label": "Corinthians",
  "logo": "corinthians.webp"
 },
 {
  "id": "flamengo",
  "value": "Flamengo",
  "label": "Flamengo",
  "logo": "flamengo.webp"
 },
 {
  "id": "santos-fc",
  "value": "Santos FC",
  "label": "Santos FC",
  "logo": "santos-fc.webp"
 },
 {
  "id": "sao-paulo-fc",
  "value": "São Paulo FC",
  "label": "São Paulo FC",
  "logo": "sao-paulo-fc.webp"
 },
 {
  "id": "fc-dinamo-tbilisi",
  "value": "FC Dinamo Tbilisi",
  "label": "FC Dinamo Tbilisi",
  "logo": "fc-dinamo-tbilisi.webp"
 },
 {
  "id": "fc-dinamo-batumi",
  "value": "FC Dinamo Batumi",
  "label": "FC Dinamo Batumi",
  "logo": "fc-dinamo-batumi.webp"
 },
 {
  "id": "fc-torpedo-kutaisi",
  "value": "FC Torpedo Kutaisi",
  "label": "FC Torpedo Kutaisi",
  "logo": "fc-torpedo-kutaisi.webp"
 },
 {
  "id": "fc-dila-gori",
  "value": "FC Dila Gori",
  "label": "FC Dila Gori",
  "logo": "fc-dila-gori.webp"
 },
 {
  "id": "fc-samtredia",
  "value": "FC Samtredia",
  "label": "FC Samtredia",
  "logo": "fc-samtredia.webp"
 },
 {
  "id": "fc-kolkheti-1913-poti",
  "value": "FC Kolkheti-1913 Poti",
  "label": "FC Kolkheti-1913 Poti",
  "logo": "fc-kolkheti-1913-poti.webp"
 },
 {
  "id": "fc-iberia-1999",
  "value": "FC Iberia 1999",
  "label": "FC Iberia 1999",
  "logo": "fc-iberia-1999.webp"
 },
 {
  "id": "zlatan-fc",
  "value": "Zlatan F.C.",
  "label": "Zlatan F.C.",
  "logo": "zlatan-fc.webp"
 },
 {
  "id": "wl-al-nassr",
  "value": "Al Nassr",
  "label": "Al Nassr",
  "logo": "wl-al-nassr.png"
 },
 {
  "id": "wl-al-qadsiah",
  "value": "Al Qadsiah",
  "label": "Al Qadsiah",
  "logo": "wl-al-qadsiah.png"
 },
 {
  "id": "wl-ales",
  "value": "Alès",
  "label": "Alès",
  "logo": "wl-ales.png"
 },
 {
  "id": "wl-atletico-mineiro",
  "value": "Atlético Mineiro",
  "label": "Atlético Mineiro",
  "logo": "wl-atletico-mineiro.png"
 },
 {
  "id": "wl-banfield",
  "value": "Banfield",
  "label": "Banfield",
  "logo": "wl-banfield.png"
 },
 {
  "id": "wl-basel",
  "value": "Basel",
  "label": "Basel",
  "logo": "wl-basel.png"
 },
 {
  "id": "wl-besiktas",
  "value": "Beşiktaş",
  "label": "Beşiktaş",
  "logo": "wl-besiktas.png"
 },
 {
  "id": "wl-bordeaux",
  "value": "Bordeaux",
  "label": "Bordeaux",
  "logo": "wl-bordeaux.png"
 },
 {
  "id": "wl-bordeaux-b",
  "value": "Bordeaux B",
  "label": "Bordeaux B",
  "logo": "wl-bordeaux-b.png"
 },
 {
  "id": "wl-botafogo",
  "value": "Botafogo",
  "label": "Botafogo",
  "logo": "wl-botafogo.png"
 },
 {
  "id": "wl-brescia",
  "value": "Brescia",
  "label": "Brescia",
  "logo": "wl-brescia.png"
 },
 {
  "id": "wl-chemnitzer-fc",
  "value": "Chemnitzer FC",
  "label": "Chemnitzer FC",
  "logo": "wl-chemnitzer-fc.png"
 },
 {
  "id": "wl-chicago-fire",
  "value": "Chicago Fire",
  "label": "Chicago Fire",
  "logo": "wl-chicago-fire.png"
 },
 {
  "id": "wl-cobreloa",
  "value": "Cobreloa",
  "label": "Cobreloa",
  "logo": "wl-cobreloa.png"
 },
 {
  "id": "wl-como",
  "value": "Como",
  "label": "Como",
  "logo": "wl-como.png"
 },
 {
  "id": "wl-cruzeiro",
  "value": "Cruzeiro",
  "label": "Cruzeiro",
  "logo": "wl-cruzeiro.png"
 },
 {
  "id": "wl-cska-sofia",
  "value": "CSKA Sofia",
  "label": "CSKA Sofia",
  "logo": "wl-cska-sofia.png"
 },
 {
  "id": "wl-dinamo-zagreb",
  "value": "Dinamo Zagreb",
  "label": "Dinamo Zagreb",
  "logo": "wl-dinamo-zagreb.png"
 },
 {
  "id": "wl-dynamo-kyiv",
  "value": "Dynamo Kyiv",
  "label": "Dynamo Kyiv",
  "logo": "wl-dynamo-kyiv.png"
 },
 {
  "id": "wl-eibar",
  "value": "Eibar",
  "label": "Eibar",
  "logo": "wl-eibar.png"
 },
 {
  "id": "wl-fiorentina",
  "value": "Fiorentina",
  "label": "Fiorentina",
  "logo": "wl-fiorentina.png"
 },
 {
  "id": "wl-fluminense",
  "value": "Fluminense",
  "label": "Fluminense",
  "logo": "wl-fluminense.png"
 },
 {
  "id": "wl-fulham",
  "value": "Fulham",
  "label": "Fulham",
  "logo": "wl-fulham.png"
 },
 {
  "id": "wl-galatasaray",
  "value": "Galatasaray",
  "label": "Galatasaray",
  "logo": "wl-galatasaray.png"
 },
 {
  "id": "wl-genk",
  "value": "Genk",
  "label": "Genk",
  "logo": "wl-genk.png"
 },
 {
  "id": "wl-go-ahead-eagles",
  "value": "Go Ahead Eagles",
  "label": "Go Ahead Eagles",
  "logo": "wl-go-ahead-eagles.png"
 },
 {
  "id": "wl-gremio",
  "value": "Grêmio",
  "label": "Grêmio",
  "logo": "wl-gremio.png"
 },
 {
  "id": "wl-groningen",
  "value": "Groningen",
  "label": "Groningen",
  "logo": "wl-groningen.png"
 },
 {
  "id": "wl-internacional",
  "value": "Internacional",
  "label": "Internacional",
  "logo": "wl-internacional.png"
 },
 {
  "id": "wl-internazionale",
  "value": "Internazionale",
  "label": "Internazionale",
  "logo": "wl-internazionale.png"
 },
 {
  "id": "wl-juventude",
  "value": "Juventude",
  "label": "Juventude",
  "logo": "wl-juventude.png"
 },
 {
  "id": "wl-kaiserslautern",
  "value": "Kaiserslautern",
  "label": "Kaiserslautern",
  "logo": "wl-kaiserslautern.png"
 },
 {
  "id": "wl-la-galaxy",
  "value": "LA Galaxy",
  "label": "LA Galaxy",
  "logo": "wl-la-galaxy.png"
 },
 {
  "id": "wl-liefering",
  "value": "Liefering",
  "label": "Liefering",
  "logo": "wl-liefering.png"
 },
 {
  "id": "wl-malmo-ff",
  "value": "Malmö FF",
  "label": "Malmö FF",
  "logo": "wl-malmo-ff.png"
 },
 {
  "id": "wl-marseille",
  "value": "Marseille",
  "label": "Marseille",
  "logo": "wl-marseille.png"
 },
 {
  "id": "wl-metz",
  "value": "Metz",
  "label": "Metz",
  "logo": "wl-metz.png"
 },
 {
  "id": "wl-millonarios",
  "value": "Millonarios",
  "label": "Millonarios",
  "logo": "wl-millonarios.png"
 },
 {
  "id": "wl-monterrey",
  "value": "Monterrey",
  "label": "Monterrey",
  "logo": "wl-monterrey.png"
 },
 {
  "id": "wl-nancy",
  "value": "Nancy",
  "label": "Nancy",
  "logo": "wl-nancy.png"
 },
 {
  "id": "wl-palmeiras",
  "value": "Palmeiras",
  "label": "Palmeiras",
  "logo": "wl-palmeiras.png"
 },
 {
  "id": "wl-queens-park-rangers",
  "value": "Queens Park Rangers",
  "label": "Queens Park Rangers",
  "logo": "wl-queens-park-rangers.png"
 },
 {
  "id": "wl-rennes",
  "value": "Rennes",
  "label": "Rennes",
  "logo": "wl-rennes.png"
 },
 {
  "id": "wl-salernitana",
  "value": "Salernitana",
  "label": "Salernitana",
  "logo": "wl-salernitana.png"
 },
 {
  "id": "wl-udinese",
  "value": "Udinese",
  "label": "Udinese",
  "logo": "wl-udinese.png"
 },
 {
  "id": "wl-vissel-kobe",
  "value": "Vissel Kobe",
  "label": "Vissel Kobe",
  "logo": "wl-vissel-kobe.png"
 },
 {
  "id": "wl-wolfsburg",
  "value": "Wolfsburg",
  "label": "Wolfsburg",
  "logo": "wl-wolfsburg.png"
 },
 {
  "id": "wl-znicz-pruszkow",
  "value": "Znicz Pruszków",
  "label": "Znicz Pruszków",
  "logo": "wl-znicz-pruszkow.png"
 },
 {
  "id": "wl-al-mokawloon",
  "value": "Al Mokawloon",
  "label": "Al Mokawloon",
  "logo": "wl-al-mokawloon.png"
 },
 {
  "id": "wl-al-duhail",
  "value": "Al-Duhail",
  "label": "Al-Duhail",
  "logo": "wl-al-duhail.png"
 },
 {
  "id": "wl-al-ettifaq",
  "value": "Al-Ettifaq",
  "label": "Al-Ettifaq",
  "logo": "wl-al-ettifaq.png"
 },
 {
  "id": "wl-al-gharafa",
  "value": "Al-Gharafa",
  "label": "Al-Gharafa",
  "logo": "wl-al-gharafa.png"
 },
 {
  "id": "wl-al-ittihad",
  "value": "Al-Ittihad",
  "label": "Al-Ittihad",
  "logo": "wl-al-ittihad.png"
 },
 {
  "id": "wl-al-rayyan",
  "value": "Al-Rayyan",
  "label": "Al-Rayyan",
  "logo": "wl-al-rayyan.png"
 },
 {
  "id": "wl-anderlecht",
  "value": "Anderlecht",
  "label": "Anderlecht",
  "logo": "wl-anderlecht.png"
 },
 {
  "id": "wl-anzhi-makhachkala",
  "value": "Anzhi Makhachkala",
  "label": "Anzhi Makhachkala",
  "logo": "wl-anzhi-makhachkala.png"
 },
 {
  "id": "wl-auxerre",
  "value": "Auxerre",
  "label": "Auxerre",
  "logo": "wl-auxerre.png"
 },
 {
  "id": "wl-barnet",
  "value": "Barnet",
  "label": "Barnet",
  "logo": "wl-barnet.png"
 },
 {
  "id": "wl-bayer-leverkusen",
  "value": "Bayer Leverkusen",
  "label": "Bayer Leverkusen",
  "logo": "wl-bayer-leverkusen.png"
 },
 {
  "id": "wl-benfica",
  "value": "Benfica",
  "label": "Benfica",
  "logo": "wl-benfica.png"
 },
 {
  "id": "wl-beveren",
  "value": "Beveren",
  "label": "Beveren",
  "logo": "wl-beveren.png"
 },
 {
  "id": "wl-birmingham-city",
  "value": "Birmingham City",
  "label": "Birmingham City",
  "logo": "wl-birmingham-city.png"
 },
 {
  "id": "wl-bolton-wanderers",
  "value": "Bolton Wanderers",
  "label": "Bolton Wanderers",
  "logo": "wl-bolton-wanderers.png"
 },
 {
  "id": "wl-boulogne",
  "value": "Boulogne",
  "label": "Boulogne",
  "logo": "wl-boulogne.png"
 },
 {
  "id": "wl-bournemouth",
  "value": "Bournemouth",
  "label": "Bournemouth",
  "logo": "wl-bournemouth.png"
 },
 {
  "id": "wl-brentford",
  "value": "Brentford",
  "label": "Brentford",
  "logo": "wl-brentford.png"
 },
 {
  "id": "wl-brest",
  "value": "Brest",
  "label": "Brest",
  "logo": "wl-brest.png"
 },
 {
  "id": "wl-caen",
  "value": "Caen",
  "label": "Caen",
  "logo": "wl-caen.png"
 },
 {
  "id": "wl-cannes",
  "value": "Cannes",
  "label": "Cannes",
  "logo": "wl-cannes.png"
 },
 {
  "id": "wl-cardiff-city",
  "value": "Cardiff City",
  "label": "Cardiff City",
  "logo": "wl-cardiff-city.png"
 },
 {
  "id": "wl-colo-colo",
  "value": "Colo-Colo",
  "label": "Colo-Colo",
  "logo": "wl-colo-colo.png"
 },
 {
  "id": "wl-coventry-city",
  "value": "Coventry City",
  "label": "Coventry City",
  "logo": "wl-coventry-city.png"
 },
 {
  "id": "wl-crystal-palace",
  "value": "Crystal Palace",
  "label": "Crystal Palace",
  "logo": "wl-crystal-palace.png"
 },
 {
  "id": "wl-cska-moscow",
  "value": "CSKA Moscow",
  "label": "CSKA Moscow",
  "logo": "wl-cska-moscow.png"
 },
 {
  "id": "wl-d-c-united",
  "value": "D.C. United",
  "label": "D.C. United",
  "logo": "wl-d-c-united.png"
 },
 {
  "id": "wl-den-bosch",
  "value": "Den Bosch",
  "label": "Den Bosch",
  "logo": "wl-den-bosch.png"
 },
 {
  "id": "wl-derby-county",
  "value": "Derby County",
  "label": "Derby County",
  "logo": "wl-derby-county.png"
 },
 {
  "id": "wl-dijon",
  "value": "Dijon",
  "label": "Dijon",
  "logo": "wl-dijon.png"
 },
 {
  "id": "wl-emirates-club",
  "value": "Emirates Club",
  "label": "Emirates Club",
  "logo": "wl-emirates-club.png"
 },
 {
  "id": "wl-envigado",
  "value": "Envigado",
  "label": "Envigado",
  "logo": "wl-envigado.png"
 },
 {
  "id": "wl-espanyol",
  "value": "Espanyol",
  "label": "Espanyol",
  "logo": "wl-espanyol.png"
 },
 {
  "id": "wl-fenerbahce",
  "value": "Fenerbahçe",
  "label": "Fenerbahçe",
  "logo": "wl-fenerbahce.png"
 },
 {
  "id": "wl-heerenveen",
  "value": "Heerenveen",
  "label": "Heerenveen",
  "logo": "wl-heerenveen.png"
 },
 {
  "id": "wl-inter-miami",
  "value": "Inter Miami",
  "label": "Inter Miami",
  "logo": "wl-inter-miami.png"
 },
 {
  "id": "wl-inter-zapresic",
  "value": "Inter Zaprešić",
  "label": "Inter Zaprešić",
  "logo": "wl-inter-zapresic.png"
 },
 {
  "id": "wl-lech-poznan",
  "value": "Lech Poznań",
  "label": "Lech Poznań",
  "logo": "wl-lech-poznan.png"
 },
 {
  "id": "wl-leyton-orient",
  "value": "Leyton Orient",
  "label": "Leyton Orient",
  "logo": "wl-leyton-orient.png"
 },
 {
  "id": "wl-lille",
  "value": "Lille",
  "label": "Lille",
  "logo": "wl-lille.png"
 },
 {
  "id": "wl-lyon",
  "value": "Lyon",
  "label": "Lyon",
  "logo": "wl-lyon.png"
 },
 {
  "id": "wl-malaga",
  "value": "Málaga",
  "label": "Málaga",
  "logo": "wl-malaga.png"
 },
 {
  "id": "wl-mallorca",
  "value": "Mallorca",
  "label": "Mallorca",
  "logo": "wl-mallorca.png"
 },
 {
  "id": "wl-maritimo",
  "value": "Marítimo",
  "label": "Marítimo",
  "logo": "wl-maritimo.png"
 },
 {
  "id": "wl-marsala",
  "value": "Marsala",
  "label": "Marsala",
  "logo": "wl-marsala.png"
 },
 {
  "id": "wl-martigues",
  "value": "Martigues",
  "label": "Martigues",
  "logo": "wl-martigues.png"
 },
 {
  "id": "wl-metalurh-donetsk",
  "value": "Metalurh Donetsk",
  "label": "Metalurh Donetsk",
  "logo": "wl-metalurh-donetsk.png"
 },
 {
  "id": "wl-millwall",
  "value": "Millwall",
  "label": "Millwall",
  "logo": "wl-millwall.png"
 },
 {
  "id": "wl-monza",
  "value": "Monza",
  "label": "Monza",
  "logo": "wl-monza.png"
 },
 {
  "id": "wl-new-york-city-fc",
  "value": "New York City FC",
  "label": "New York City FC",
  "logo": "wl-new-york-city-fc.png"
 },
 {
  "id": "wl-new-york-red-bulls",
  "value": "New York Red Bulls",
  "label": "New York Red Bulls",
  "logo": "wl-new-york-red-bulls.png"
 },
 {
  "id": "wl-nice",
  "value": "Nice",
  "label": "Nice",
  "logo": "wl-nice.png"
 },
 {
  "id": "wl-nimes",
  "value": "Nîmes",
  "label": "Nîmes",
  "logo": "wl-nimes.png"
 },
 {
  "id": "wl-norwich-city",
  "value": "Norwich City",
  "label": "Norwich City",
  "logo": "wl-norwich-city.png"
 },
 {
  "id": "wl-olympiacos",
  "value": "Olympiacos",
  "label": "Olympiacos",
  "logo": "wl-olympiacos.png"
 },
 {
  "id": "wl-orlando-city",
  "value": "Orlando City",
  "label": "Orlando City",
  "logo": "wl-orlando-city.png"
 },
 {
  "id": "wl-paok",
  "value": "PAOK",
  "label": "PAOK",
  "logo": "wl-paok.png"
 },
 {
  "id": "wl-perth-glory",
  "value": "Perth Glory",
  "label": "Perth Glory",
  "logo": "wl-perth-glory.png"
 },
 {
  "id": "wl-qingdao-huanghai",
  "value": "Qingdao Huanghai",
  "label": "Qingdao Huanghai",
  "logo": "wl-qingdao-huanghai.png"
 },
 {
  "id": "wl-queretaro",
  "value": "Querétaro",
  "label": "Querétaro",
  "logo": "wl-queretaro.png"
 },
 {
  "id": "wl-rayo-vallecano",
  "value": "Rayo Vallecano",
  "label": "Rayo Vallecano",
  "logo": "wl-rayo-vallecano.png"
 },
 {
  "id": "wl-rb-leipzig",
  "value": "RB Leipzig",
  "label": "RB Leipzig",
  "logo": "wl-rb-leipzig.png"
 },
 {
  "id": "wl-red-bull-salzburg",
  "value": "Red Bull Salzburg",
  "label": "Red Bull Salzburg",
  "logo": "wl-red-bull-salzburg.png"
 },
 {
  "id": "wl-reggina",
  "value": "Reggina",
  "label": "Reggina",
  "logo": "wl-reggina.png"
 },
 {
  "id": "wl-rosario-central",
  "value": "Rosario Central",
  "label": "Rosario Central",
  "logo": "wl-rosario-central.png"
 },
 {
  "id": "wl-sagan-tosu",
  "value": "Sagan Tosu",
  "label": "Sagan Tosu",
  "logo": "wl-sagan-tosu.png"
 },
 {
  "id": "wl-southampton",
  "value": "Southampton",
  "label": "Southampton",
  "logo": "wl-southampton.png"
 },
 {
  "id": "wl-sporting-gijon",
  "value": "Sporting Gijón",
  "label": "Sporting Gijón",
  "logo": "wl-sporting-gijon.png"
 },
 {
  "id": "wl-stoke-city",
  "value": "Stoke City",
  "label": "Stoke City",
  "logo": "wl-stoke-city.png"
 },
 {
  "id": "wl-vasco-da-gama",
  "value": "Vasco da Gama",
  "label": "Vasco da Gama",
  "logo": "wl-vasco-da-gama.png"
 },
 {
  "id": "wl-west-bromwich-albion",
  "value": "West Bromwich Albion",
  "label": "West Bromwich Albion",
  "logo": "wl-west-bromwich-albion.png"
 },
 {
  "id": "wl-willem-ii",
  "value": "Willem II",
  "label": "Willem II",
  "logo": "wl-willem-ii.png"
 },
 {
  "id": "wl-zaragoza",
  "value": "Zaragoza",
  "label": "Zaragoza",
  "logo": "wl-zaragoza.png"
 },
 {
  "id": "wl-zrinjski",
  "value": "Zrinjski",
  "label": "Zrinjski",
  "logo": "wl-zrinjski.png"
 },
 {
  "id": "wl-adana-demirspor",
  "value": "Adana Demirspor",
  "label": "Adana Demirspor",
  "logo": "wl-adana-demirspor.png"
 },
 {
  "id": "wl-all-boys",
  "value": "All Boys",
  "label": "All Boys",
  "logo": "wl-all-boys.png"
 },
 {
  "id": "wl-basaksehir",
  "value": "Başakşehir",
  "label": "Başakşehir",
  "logo": "wl-basaksehir.png"
 },
 {
  "id": "wl-bryne",
  "value": "Bryne",
  "label": "Bryne",
  "logo": "wl-bryne.png"
 },
 {
  "id": "wl-danubio",
  "value": "Danubio",
  "label": "Danubio",
  "logo": "wl-danubio.png"
 },
 {
  "id": "wl-dynamo-moscow",
  "value": "Dynamo Moscow",
  "label": "Dynamo Moscow",
  "logo": "wl-dynamo-moscow.png"
 },
 {
  "id": "wl-el-mokawloon",
  "value": "El Mokawloon",
  "label": "El Mokawloon",
  "logo": "wl-el-mokawloon.png"
 },
 {
  "id": "wl-estudiantes-de-la-plata",
  "value": "Estudiantes",
  "label": "Estudiantes",
  "logo": "wl-estudiantes-de-la-plata.png"
 },
 {
  "id": "wl-hamburger-sv",
  "value": "Hamburg",
  "label": "Hamburg",
  "logo": "wl-hamburger-sv.png"
 },
 {
  "id": "wl-hebei-china-fortune",
  "value": "Hebei China Fortune",
  "label": "Hebei China Fortune",
  "logo": "wl-hebei-china-fortune.png"
 },
 {
  "id": "wl-los-angeles-fc",
  "value": "Los Angeles FC",
  "label": "Los Angeles FC",
  "logo": "wl-los-angeles-fc.png"
 },
 {
  "id": "wl-melbourne-victory",
  "value": "Melbourne Victory",
  "label": "Melbourne Victory",
  "logo": "wl-melbourne-victory.png"
 },
 {
  "id": "wl-molde",
  "value": "Molde",
  "label": "Molde",
  "logo": "wl-molde.png"
 },
 {
  "id": "wl-club-nacional-de-football",
  "value": "Nacional",
  "label": "Nacional",
  "logo": "wl-club-nacional-de-football.png"
 },
 {
  "id": "wl-trabzonspor",
  "value": "Trabzonspor",
  "label": "Trabzonspor",
  "logo": "wl-trabzonspor.png"
 },
 {
  "id": "wl-venezia",
  "value": "Venezia",
  "label": "Venezia",
  "logo": "wl-venezia.png"
 },
 {
  "id": "wl-vfl-wolfsburg",
  "value": "VfL Wolfsburg",
  "label": "VfL Wolfsburg",
  "logo": "wl-vfl-wolfsburg.png"
 },
 {
  "id": "wl-shanghai-shenhua",
  "value": "Shanghai Shenhua",
  "label": "Shanghai Shenhua",
  "logo": "wl-shanghai-shenhua.png"
 },
 {
  "id": "wl-nurnberg",
  "value": "1. FC Nürnberg",
  "label": "1. FC Nürnberg",
  "logo": "wl-nurnberg.png"
 },
 {
  "id": "wl-al-shabab",
  "value": "Al Shabab",
  "label": "Al Shabab",
  "logo": "wl-al-shabab.png"
 },
 {
  "id": "wl-al-ahli",
  "value": "Al-Ahli",
  "label": "Al-Ahli",
  "logo": "wl-al-ahli.png"
 },
 {
  "id": "wl-al-arabi",
  "value": "Al-Arabi",
  "label": "Al-Arabi",
  "logo": "wl-al-arabi.png"
 },
 {
  "id": "wl-alania",
  "value": "Alania Vladikavkaz",
  "label": "Alania Vladikavkaz",
  "logo": "wl-alania.png"
 },
 {
  "id": "wl-anorthosis",
  "value": "Anorthosis Famagusta",
  "label": "Anorthosis Famagusta",
  "logo": "wl-anorthosis.png"
 },
 {
  "id": "wl-bastia",
  "value": "Bastia",
  "label": "Bastia",
  "logo": "wl-bastia.png"
 },
 {
  "id": "wl-grasshoppers",
  "value": "Grasshoppers",
  "label": "Grasshoppers",
  "logo": "wl-grasshoppers.png"
 },
 {
  "id": "wl-grosseto",
  "value": "Grosseto",
  "label": "Grosseto",
  "logo": "wl-grosseto.png"
 },
 {
  "id": "wl-hajduk-split",
  "value": "Hajduk Split",
  "label": "Hajduk Split",
  "logo": "wl-hajduk-split.png"
 },
 {
  "id": "wl-inter-baku",
  "value": "Inter Baku",
  "label": "Inter Baku",
  "logo": "wl-inter-baku.png"
 },
 {
  "id": "wl-karlsruher",
  "value": "Karlsruher SC",
  "label": "Karlsruher SC",
  "logo": "wl-karlsruher.png"
 },
 {
  "id": "wl-lanceros",
  "value": "Lanceros Boyacá",
  "label": "Lanceros Boyacá",
  "logo": "wl-lanceros.png"
 },
 {
  "id": "wl-lask",
  "value": "LASK",
  "label": "LASK",
  "logo": "wl-lask.png"
 },
 {
  "id": "wl-le-havre",
  "value": "Le Havre",
  "label": "Le Havre",
  "logo": "wl-le-havre.png"
 },
 {
  "id": "wl-luzern",
  "value": "Luzern",
  "label": "Luzern",
  "logo": "wl-luzern.png"
 },
 {
  "id": "wl-notts-county",
  "value": "Notts County",
  "label": "Notts County",
  "logo": "wl-notts-county.png"
 },
 {
  "id": "wl-perugia",
  "value": "Perugia",
  "label": "Perugia",
  "logo": "wl-perugia.png"
 },
 {
  "id": "wl-pescara",
  "value": "Pescara",
  "label": "Pescara",
  "logo": "wl-pescara.png"
 },
 {
  "id": "wl-portsmouth",
  "value": "Portsmouth",
  "label": "Portsmouth",
  "logo": "wl-portsmouth.png"
 },
 {
  "id": "wl-quimper",
  "value": "Quimper",
  "label": "Quimper",
  "logo": "wl-quimper.png"
 },
 {
  "id": "wl-red-star",
  "value": "Red Star Belgrade",
  "label": "Red Star Belgrade",
  "logo": "wl-red-star.png"
 },
 {
  "id": "wl-rw-ahlen",
  "value": "Rot Weiss Ahlen",
  "label": "Rot Weiss Ahlen",
  "logo": "wl-rw-ahlen.png"
 },
 {
  "id": "wl-rubin-kazan",
  "value": "Rubin Kazan",
  "label": "Rubin Kazan",
  "logo": "wl-rubin-kazan.png"
 },
 {
  "id": "wl-saarbrucken",
  "value": "Saarbrücken",
  "label": "Saarbrücken",
  "logo": "wl-saarbrucken.png"
 },
 {
  "id": "wl-sheffield-united",
  "value": "Sheffield United",
  "label": "Sheffield United",
  "logo": "wl-sheffield-united.png"
 },
 {
  "id": "wl-siena",
  "value": "Siena",
  "label": "Siena",
  "logo": "wl-siena.png"
 },
 {
  "id": "wl-sion",
  "value": "Sion",
  "label": "Sion",
  "logo": "wl-sion.png"
 },
 {
  "id": "wl-spartak-moscow",
  "value": "Spartak Moscow",
  "label": "Spartak Moscow",
  "logo": "wl-spartak-moscow.png"
 },
 {
  "id": "wl-spartak-subotica",
  "value": "Spartak Subotica",
  "label": "Spartak Subotica",
  "logo": "wl-spartak-subotica.png"
 },
 {
  "id": "wl-st-gallen",
  "value": "St. Gallen",
  "label": "St. Gallen",
  "logo": "wl-st-gallen.png"
 },
 {
  "id": "wl-talleres",
  "value": "Talleres",
  "label": "Talleres",
  "logo": "wl-talleres.png"
 },
 {
  "id": "wl-teplice",
  "value": "Teplice",
  "label": "Teplice",
  "logo": "wl-teplice.png"
 },
 {
  "id": "wl-toulouse",
  "value": "Toulouse",
  "label": "Toulouse",
  "logo": "wl-toulouse.png"
 },
 {
  "id": "wl-usti",
  "value": "Ústí nad Labem",
  "label": "Ústí nad Labem",
  "logo": "wl-usti.png"
 },
 {
  "id": "wl-lubeck",
  "value": "VfB Lübeck",
  "label": "VfB Lübeck",
  "logo": "wl-lubeck.png"
 },
 {
  "id": "wl-bochum",
  "value": "VfL Bochum",
  "label": "VfL Bochum",
  "logo": "wl-bochum.png"
 },
 {
  "id": "wl-zeljeznicar",
  "value": "Željezničar",
  "label": "Željezničar",
  "logo": "wl-zeljeznicar.png"
 },
 {
  "id": "wl-zurich",
  "value": "Zürich",
  "label": "Zürich",
  "logo": "wl-zurich.png"
 }
];
