/**
 * Encrypts the Buscaminas boards (clues, player cards and answers) from the web repo's full day
 * files into the backend, which is their only public source: it serves each board once its day
 * is playable, and never the answers of a live round.
 *
 *   npm run buscaminas:content [-- <srcDir>]
 *
 * <srcDir> is either a directory of YYYY-MM-DD.json day files or a web repo root (its
 * scripts/buscaminas/full/days is used; default: the sibling buscaminas-web or
 * frontend-web-next checkout). The key comes from BUSCAMINAS_CONTENT_KEY (environment, else
 * the backend .env).
 *
 * Writes only src/modules/buscaminas/content/content.enc.ts: the backend repo is public, so
 * plaintext boards must never be committed. A TS module (not JSON) so tsc ships it in dist.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { config as loadDotenv } from 'dotenv';
import { LAUNCH_DAY, PUBLISHED_DAYS, addDays } from '../src/modules/buscaminas/buscaminas.days.js';
import { openContent, parseDay, sealContent, type SealedContent } from '../src/modules/buscaminas/buscaminas.sealed.js';

const DAY_FILE = /^\d{4}-\d{2}-\d{2}\.json$/;
const OUT_FILE = 'content.enc.ts';

const backendRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const contentDir = process.env.BUSCAMINAS_CONTENT_OUT_DIR ?? join(backendRoot, 'src/modules/buscaminas/content');

const dayFiles = (dir: string): string[] =>
  existsSync(dir) && statSync(dir).isDirectory() ? readdirSync(dir).filter((f) => DAY_FILE.test(f)).sort() : [];

const fullDays = (root: string): string | null => {
  const dir = join(root, 'scripts/buscaminas/full/days');
  return dayFiles(dir).length > 0 ? dir : null;
};

function resolveSource(arg: string | undefined): string {
  if (arg) {
    const dir = resolve(arg);
    if (dayFiles(dir).length > 0) return dir;
    const viaRoot = fullDays(dir);
    if (viaRoot) return viaRoot;
    throw new Error(`No day files found under ${dir}`);
  }
  const roots = [process.env.BUSCAMINAS_WEB_DIR, join(backendRoot, '../buscaminas-web'), join(backendRoot, '../frontend-web-next')]
    .filter((r): r is string => Boolean(r));
  for (const root of roots) {
    const src = fullDays(root);
    if (src) return src;
  }
  throw new Error(`No Buscaminas content source found (tried ${roots.join(', ')}); pass <srcDir>`);
}

function checkCalendar(files: string[]): void {
  if (files.length !== PUBLISHED_DAYS) throw new Error(`expected ${PUBLISHED_DAYS} day files, found ${files.length}`);
  files.forEach((file, i) => {
    const expected = `${addDays(LAUNCH_DAY, i)}.json`;
    if (file !== expected) throw new Error(`days must be contiguous from ${LAUNCH_DAY}: expected ${expected}, found ${file}`);
  });
}

async function readExisting(file: string): Promise<SealedContent | null> {
  if (!existsSync(file)) return null;
  try {
    return ((await import(pathToFileURL(file).href)) as { BUSCAMINAS_SEALED_CONTENT: SealedContent }).BUSCAMINAS_SEALED_CONTENT;
  } catch {
    return null;
  }
}

async function main(): Promise<void> {
  if (process.env.BUSCAMINAS_CONTENT_KEY === undefined) loadDotenv({ path: join(backendRoot, '.env') });
  const key = process.env.BUSCAMINAS_CONTENT_KEY;
  if (!key) throw new Error('BUSCAMINAS_CONTENT_KEY is not set (64 hex chars; environment or backend .env)');

  const src = resolveSource(process.argv[2]);
  const files = dayFiles(src);
  checkCalendar(files);
  const days = files.map((file, i) => {
    const day = parseDay(file, JSON.parse(readFileSync(join(src, file), 'utf8')));
    if (`${day.day}.json` !== file) throw new Error(`${file}: day does not match file name`);
    if (day.number !== i + 1) throw new Error(`${file}: number must be ${i + 1}`);
    return day;
  });

  mkdirSync(contentDir, { recursive: true });
  rmSync(join(contentDir, 'days'), { recursive: true, force: true });
  rmSync(join(contentDir, 'content.generated.ts'), { force: true });

  const out = join(contentDir, OUT_FILE);
  const existing = await readExisting(out);
  let unchanged = false;
  try {
    unchanged = existing !== null && JSON.stringify(openContent(existing, key)) === JSON.stringify(days);
  } catch {
    unchanged = false;
  }
  if (!unchanged) {
    writeFileSync(
      out,
      `// Generated by scripts/buscaminas-copy-content.ts (AES-256-GCM, key BUSCAMINAS_CONTENT_KEY); do not edit.\n` +
        `import type { SealedContent } from '../buscaminas.sealed.js';\n\n` +
        `export const BUSCAMINAS_SEALED_CONTENT: SealedContent = ${JSON.stringify(sealContent(days, key))};\n`,
    );
  }
  console.log(`[buscaminas] ${unchanged ? 'unchanged' : 'encrypted'} ${days.length} days (${days[0].day} … ${days[days.length - 1].day}) from ${src}`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
