/**
 * Re-vendor the club crest registry from the web app into the backend so the
 * WL content import can tell the editor which career clubs have no crest.
 * Source of truth stays frontend-web-next/src/data/clubs.json (crests are
 * served from imgs/club-logos on both Supabase projects).
 *
 * Usage: npx tsx scripts/sync-wl-crest-registry.ts [path/to/clubs.json]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const src = process.argv[2] ?? resolve(process.cwd(), '../frontend-web-next/src/data/clubs.json');
const rows = JSON.parse(readFileSync(src, 'utf8')) as Array<{ id: string; value: string; label: string; logo: string }>;
const slim = rows.map((c) => ({ id: c.id, value: c.value, label: c.label, logo: c.logo }));
const out = resolve(process.cwd(), 'src/modules/weekend-league/wl-crest-registry.data.ts');
writeFileSync(out, `// GENERATED by scripts/sync-wl-crest-registry.ts from frontend-web-next/src/data/clubs.json — do not edit.
export interface CrestRegistryRow { id: string; value: string; label: string; logo: string }
export const CREST_REGISTRY: readonly CrestRegistryRow[] = ${JSON.stringify(slim, null, 1)};
`);
console.log(`wrote ${slim.length} clubs → ${out}`);
