import test from 'node:test';
import assert from 'node:assert/strict';
import { buildQuestionManifest, contentHash } from '../../scripts/release/question-manifest.mjs';
const category={id:'cat',slug:'football',name:{en:'Football'}};
function snapshot(project,questions){return {format:1,project,categories:[category],questions:questions.map(q=>({id:q.id,category_id:'cat',type:'mcq_single',difficulty:'easy',status:'published',prompt:{en:'A football question'},explanation:null,ranked_eligible:true,visibility:'public',...q})),payloads:questions.map(q=>({id:'payload-'+q.id,question_id:q.id,payload:{type:'mcq_single',options:[{id:'a',text:{en:'Answer'},is_correct:true}]}}))};}
test('keeps both independent additions and conflicting production edits in the inventory',()=>{const source=snapshot('stage',[{id:'same',prompt:{en:'Stage edit'}},{id:'new'}]);const target=snapshot('prod',[{id:'same',prompt:{en:'Production edit'}},{id:'prod-only'}]);const before=structuredClone({source,target});const m=buildQuestionManifest(source,target);assert.equal(m.executable,false);assert.equal(m.entries.find(e=>e.sourceId==='same').disposition,'preserve-target-review-conflict');assert.deepEqual(m.entries.find(e=>e.sourceId==='same').changedPaths,['prompt.en']);assert.equal(m.targetOnly[0].id,'prod-only');assert.deepEqual({source,target},before);assert.equal(m.entries.length,source.questions.length);});
test('identity excludes operational authors/timestamps/history and object key order',()=>{const source=snapshot('stage',[{id:'same',created_by:'stage-user',wl_seen_count:8}]);const target=snapshot('prod',[{id:'same',created_by:'prod-user',wl_seen_count:1}]);assert.equal(buildQuestionManifest(source,target).entries[0].disposition,'identical');assert.equal(contentHash({a:1,b:2}),contentHash({b:2,a:1}));});
test('detects exact duplicate content under another ID without choosing an ID or deleting it',()=>{const m=buildQuestionManifest(snapshot('stage',[{id:'new'}]),snapshot('prod',[{id:'existing'}]));assert.equal(m.entries[0].disposition,'review-existing-identical-content');assert.equal(m.entries[0].targetId,null);assert.deepEqual(m.entries[0].exactOtherIds,['existing']);});
test('records missing locale opportunities while preserving conflicting strings',()=>{const source=snapshot('stage',[{id:'same',prompt:{en:'Same',ka:'ქართული',es:'Nuevo'}}]);const target=snapshot('prod',[{id:'same',prompt:{en:'Same',es:'Existente'}}]);assert.deepEqual(buildQuestionManifest(source,target).entries[0].missingLocalePaths,['prompt.ka']);});
test('does not attach translations to reordered answer IDs',()=>{const source=snapshot('stage',[{id:'same'}]);const target=snapshot('prod',[{id:'same'}]);source.payloads[0].payload.options[0].text.ka='ქართული';target.payloads[0].payload.options[0].id='different';assert.deepEqual(buildQuestionManifest(source,target).entries[0].missingLocalePaths,[]);});
test('never auto-publishes private, archived, draft or possible test content',()=>{const m=buildQuestionManifest(snapshot('stage',[{id:'private',visibility:'wl_private',status:'draft',prompt:{en:'e2e fixture'}}]),snapshot('prod',[]));assert.deepEqual(m.entries[0].reviewReasons,['status:draft','visibility:wl_private','possible-test-content']);assert.equal(m.entries[0].disposition,'review-addition');});
test('fails closed on missing dependencies and duplicate identities',()=>{const source=snapshot('stage',[{id:'a'}]);const target=snapshot('prod',[]);source.payloads=[];assert.throws(()=>buildQuestionManifest(source,target),/missing content dependencies/);source.questions.push(source.questions[0]);assert.throws(()=>buildQuestionManifest(source,target),/duplicate/);assert.throws(()=>buildQuestionManifest(target,target),/must differ/);});
